### ISSUE TITLE
小白问一下  那个dns.exe  打开一闪而过 不能运行 怎么解决

### ISSUE THREAD

**Issue by hongsehunli** [dowsnature/dowsDNS#10]

**Comment by lizongzeshunshun** [comment]
确认配置文件按照README修改过了？

**Comment by hongsehunli** [comment]
修改过了的

**Comment by hongsehunli** [comment]
![mmmm](https://cloud.githubusercontent.com/assets/18511495/21741166/ef13b036-d508-11e6-9a4f-f779a9f07ea7.png)
显示空白的  不知怎么回事

**Comment by downature** [comment]
1.打开cmd窗口
2.把dns.exe 文件拖放cmd窗口，回车。

**Comment by lizongzeshunshun** [comment]
DNS服务器要设置为127.0.0.1(如果配置文件里写的是127.0.0.1

**Comment by hongsehunli** [comment]
![ddddd](https://cloud.githubusercontent.com/assets/18511495/21741494/761e4bbe-d512-11e6-8c14-61a5116bafde.png)
好像还是不行

**Comment by lizongzeshunshun** [comment]
...
改完配置文件后**直接打开(双击)**`dns.exe`(此时不会有任何信息显示)，然后在**本地连接(or无线网络连接)->属性->IPV4**中选择**使用下面的DNS服务器地址**，填写**127.0.0.1**，保存。

**Comment by downature** [comment]
请确保 config.json ,rpz.json,dns.exe 这三个文件在同一个文件夹，默认就是这样。

2017年1月7日 下午7:57，"LIZONGZE" <notifications@github.com>写道：

**Comment by lizongzeshunshun** [comment]
如果非要命令行执行必须先CD到目录。
config.json文件必须在**执行启动命令的目录**，而不一定是与dns.exe同级
