### ISSUE TITLE
建议配置,增强去广告能力.

### ISSUE THREAD

**Issue by zyqf** [dowsnature/dowsDNS#12]
{
	"hosts":{
		"racaljk":"https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts",
		"yhosts":"https://raw.githubusercontent.com/vokins/yhosts/master/hosts",
		"adaway":"https://raw.githubusercontent.com/aoccin/adaway/master/hosts"
	},
	"DNSMasq":"I'm too lazy, you know",
	"jsonb64":"https://raw.githubusercontent.com/dowsnature/dowsDNS/master/data/wrcd.base64"

}

**Comment by theratlesnake** [comment]
可以说说详细怎么用吗？不懂

**Comment by zyqf** [comment]
把 'conf/data.json' 内容，替换我说的，然后更新记录就好了。

**Comment by theratlesnake** [comment]
好，我等下试试，谢啦

**Comment by theratlesnake** [comment]
请教下，请问这个新的版本怎么运行？

**Comment by zyqf** [comment]
windows 还是python，作者在主页写的很清楚了啊。

**Comment by theratlesnake** [comment]
可以了，我运行时提示【配置的DNS服务器不正确或不正确】但是可以正常上网，这个有影响吗？

**Comment by wpyok500** [comment]
mark

**Comment by downature** [comment]
@theratlesnake  没有影响，只是不支持IPv6，工作完后，有时间就解决下。
