### ISSUE TITLE
怎么自定义添加SNI代理？

### ISSUE THREAD

**Issue by ToyoDAdoubi** [dowsnature/dowsDNS#14]
怎么自定义添加SNI代理？
SNI代理设置的是 所有域名都反向代理，该如何添加？

**Comment by downature** [comment]
{
	"Remote_dns_server" : "114.114.114.114",
	"Remote_dns_port":53,
	"Rpz_json_path":"./data/rpz.json",
	"Local_dns_server" : "127.0.0.1",
	"Local_dns_port" :  53,
	"sni_proxy_on":true,
	"sni_proxy_ip":"219.76.4.3"
}

修改sni_proxy_ip的值就可以了

**Comment by wpyok500** [comment]
mark

**Comment by theratlesnake** [comment]
@downature 开发者你好，请问下，这种方法翻墙有用到谁的服务器吗？如果没有我就放心看youtube了，不用担心流量啦。

**Comment by SeaHOH** [comment]
219.76.4.3 属于 Hong Kong Telecommunications，似乎带宽比不上谷歌 IP。
