### ISSUE TITLE
请问，最多可以有多少个配置，是否支持IPV6的host?google、fackbook、twitter都可以打开，youtube不能打开?

### ISSUE THREAD

**Issue by wpyok500** [dowsnature/dowsDNS#16]
1、请问，最多可以有多少个配置，是否支持IPV6的host?
2、google、fackbook、twitter都可以打开，youtube不能打开?
3、配置是否支持本地host？

**Comment by downature** [comment]
1,可以配置多个hosts地址，上限取决你的计算机内存，不支持IPv6

2.本地hosts记录优先级高于DNS查询，这是系统决定的，Youtube 不能上？清空本地hosts。

3,同上。

另外：

清空本地hosts，Youtube还是不能上的问题，请自己找可用的SNIproxy ip地址。
