### ISSUE TITLE
配置文件是否允许注释（如在data.json配置文件中使用#注释掉某行自定义的hosts）

### ISSUE THREAD

**Issue by wpyok500** [dowsnature/dowsDNS#19]
1、配置文件是否允许注释（如在data.json配置文件中使用#注释掉某行自定义的hosts）
2、个别网站不能访问，如三立新闻网http://www.setn.com/  

3、建议加入支持本地hosts解析

**Comment by wpyok500** [comment]
1、自己在GitHub上建仓hosts文件，data.json配置文件引入后，Google可以访问但三立新闻台依旧不能访问。
2、在本地配置C:\WINDOWS\system32\drivers\etc\hosts，可以访问三立新闻台。(168.63.220.206 www.setn.com)

**Comment by OneWizard** [comment]
我记得json文件本身是不支持注释的吧。。。和软件无关

**Comment by downature** [comment]
3、建议加入支持本地hosts解析

系统hosts记录优先于DNS,不用多此一举

配置文件不知道能不能注释，下次更新会测试
