### ISSUE TITLE
Mac 下运行不需要写python2，改成python就可以了

### ISSUE THREAD

**Issue by ShawnZhong** [dowsnature/dowsDNS#22]
sudo python /Users/Shawn/Downloads/dowsDNS/run.py 
sh: python2: command not found
![image](https://cloud.githubusercontent.com/assets/6421097/22851376/21f53250-f05b-11e6-8cd6-ec2309521f0b.png)

![image](https://cloud.githubusercontent.com/assets/6421097/22851372/0e039b74-f05b-11e6-83aa-7c5899083e9c.png)

**Comment by ShawnZhong** [comment]
或者像xx-net那样判断一下
if python -V | grep -q "Python 3" ;then
    PYTHON="python2"
else
    PYTHON="python"
fi

**Comment by downature** [comment]
好的，谢谢，下次更新会改善这点的
