### ISSUE TITLE
开发计划安排

### ISSUE THREAD

**Issue by downature** [dowsnature/dowsDNS#3]
1月15日-？

* 自动更新解析记录

   * √ 初步更新：内置指定源地址定期更新 
   * 反封更新：√ (关键)记录数据加密，（×） 可存放在博客博文，(×) 贴吧帖子中。
   * 进阶更新：自定义加密，P2P去中心化（无限期哈。。不过可以借助ZERONET）

* 代码重构
   *  √  把代码写的规范，易用，把核心的内容梳理一遍，尽量通俗易懂介绍如何分析DNS报文

##  明年

* 开发移动端
   * 开发安卓客户端，无须Root，以vpn形式修正DNS数据包
   * 无移动IOS系统开发计划

* 一些特殊环境
   * 目前有些特殊环境，比如公网地址，修正数据后需要扔回去，但有些单位的机房有DNS污染设施的，会造成二次污染，目前是个别现象，无足够的信息去分析和解决。暂时无法解决

**Comment by HolaJam** [comment]
在尝试修改您的代码~如果成功会提交pr~

**Comment by theratlesnake** [comment]
支持作者，作者有twitter吗？给我关注一下吧

**Comment by ToyoDAdoubi** [comment]
看看看看~

**Comment by zyqf** [comment]
后期会加入本地缓存机制，也可能会支持edns-client-subnet and so on。。。

2017年1月16日 上午12:37，"ToyoDAdoubi" <notifications@github.com>写道：

**Comment by theratlesnake** [comment]
技术菜鸟，支持你们一下

**Comment by PvCDp** [comment]
加油，最好能不影响本地访问速度，能把本地访问和翻墙访问分开。

**Comment by theratlesnake** [comment]
@downature 祝您新年快乐，谢谢你的努力付出，也祝大家新年快乐！

**Comment by Sak1tama** [comment]
建议先开发安卓ipatables转发的方式，因为安卓的ss服务端是用vpn的方式连接的，vpn速度不快容易掉线，同一个ss安卓和电脑比速度要差一些，vpn并非最佳选项

**Comment by theratlesnake** [comment]
@Sak1tama 老哥，你在跟踪我吗？啊哈

**Comment by horizonl** [comment]
果然，，早上在安卓端尝试用termux来用dowsDNS
提示需要用管理员权限
