### ISSUE TITLE
youtube的视频播放不出来

### ISSUE THREAD

**Issue by huziyang410** [dowsnature/dowsDNS#33]

**Comment by DennisWong** [comment]
我的可以啊

**Comment by huziyang410** [comment]
恩，可以，需要等一下。
但是，这种方法可以支持ios吗？

**Comment by liuyunbin** [comment]
可以的，将 ios 域名服务器地址改了

**Comment by huziyang410** [comment]
这种情况怎么办啊

Traceback (most recent call last):
  File "start.py", line 14, in <module>
    Myip = urlR.urlopen(url).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.U

**Comment by downature** [comment]
@huziyang410 已修复
https://github.com/dowsnature/dowsDNS/commit/d202e821112e1f3839de6df1a9c696fbd9502494

**Comment by qingshuiyuyu** [comment]
==========Config===========
('Local_dns_server:', u'192.168.119.124')
('Local_dns_port:', 53)
('Remote_dns_server:', u'119.29.29.29')
('Remote_dns_port:', 53)
('Public_Server:', False)
('Your Global IP:', u'14.130.112.4')
===========Config==========
Trying start bind local IP and port ...
Bind successfully! Running ...
兄弟们，这算成功了吗？往下还有步骤吗？上不去啊

**Comment by downature** [comment]
本地DNS地址修改为：192.168.119.124

**Comment by hzy333** [comment]
没有ctr + c 退出，53的进程总是杀不完，怎么破？

**Comment by downature** [comment]
@huziyang410 最笨的办法：killall python
杀死所有python进程。

另外，请不要用 ctr + c，杀不掉的。你要么杀掉进程，要么关掉终端

**Comment by hzy333** [comment]
好的，谢谢。
> 在 2017年6月6日，下午1:50，downature <notifications@github.com> 写道：
> 
> 你要么杀掉进程，要么关掉终端

**Comment by zxb5102** [comment]
表示进入YouTube 
出现下面错误被拦截了
-----------------------------------------------------
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.
-----------------------------------------------------
感到很尴尬 希望修复

**Comment by hzy333** [comment]
突然不行了，被封了吗？不知道是不是公司的局域网的问题。

> 在 2017年6月6日，下午1:51，huziyang <1715881798@qq.com> 写道：
> 
> 好的，谢谢。
>> 在 2017年6月6日，下午1:50，downature <notifications@github.com <mailto:notifications@github.com>> 写道：
>> 
>> 你要么杀掉进程，要么关掉终端
>

**Comment by hzy333** [comment]
一直都是 timeout

> 在 2017年6月16日，上午9:43，huziyang <1715881798@qq.com> 写道：
> 
> 突然不行了，被封了吗？不知道是不是公司的局域网的问题。
> 
>> 在 2017年6月6日，下午1:51，huziyang <1715881798@qq.com <mailto:1715881798@qq.com>> 写道：
>> 
>> 好的，谢谢。
>>> 在 2017年6月6日，下午1:50，downature <notifications@github.com <mailto:notifications@github.com>> 写道：
>>> 
>>> 你要么杀掉进程，要么关掉终端
>> 
>

**Comment by hzy333** [comment]
好了，好像需要update。
> 在 2017年6月16日，上午10:09，huziyang <1715881798@qq.com> 写道：
> 
> 一直都是 timeout
> <PastedGraphic-1.png>
>> 在 2017年6月16日，上午9:43，huziyang <1715881798@qq.com <mailto:1715881798@qq.com>> 写道：
>> 
>> 突然不行了，被封了吗？不知道是不是公司的局域网的问题。
>> 
>>> 在 2017年6月6日，下午1:51，huziyang <1715881798@qq.com <mailto:1715881798@qq.com>> 写道：
>>> 
>>> 好的，谢谢。
>>>> 在 2017年6月6日，下午1:50，downature <notifications@github.com <mailto:notifications@github.com>> 写道：
>>>> 
>>>> 你要么杀掉进程，要么关掉终端
>>> 
>> 
>

**Comment by sandByMe** [comment]
==========Config===========
Local_dns_server: 127.0.0.1
Local_dns_port: 53
Remote_dns_server: 119.29.29.29
Remote_dns_port: 53
Public_Server: False
Your Global IP: 119.123.178.3
===========Config==========
Trying start bind local IP and port ...
Bind successfully! Running ...

问一下在windows上成功运行了你的程序，然后呢，我还是不能上外网。
你的这个程序只是一个demo还是具有能翻墙的效果？
如果是能翻墙，那么为什么显示成功了还是不能上外网呢？
难道是还需要做什么吗？谢谢你

**Comment by joshatt** [comment]
`
请选择后回车：
1
.
正在设置本地DNS代理，请稍等...
网络 = "本地连接"
DNS  = 127.0.0.1
.
文件名、目录名或卷标语法不正确。


本地代理已设置！
若无法使用,请手动修改系统的DNS为:127.0.0.1(默认情况)
==========Config===========
Local_dns_server: 127.0.0.1
Local_dns_port: 53
Remote_dns_server: 114.114.114.114
Remote_dns_port: 53
===========Config==========
Trying start bind local IP and port ...

Binding failed! Please run as administrator锛?

And check the local IP address and port is correct?

==========Error message==========
Traceback (most recent call last):
  File "dns.py", line 91, in <module>
socket.error: [Errno 10013]
Failed to execute script dns
请按任意键继续. . .`
报错了. 请问问题出在哪里? 好像不应该针对"本地连接", 而应该是笔记本电脑的无线连接???

**Comment by pasalai** [comment]
有可能啊，我的电脑不行，我路由器DNS是手动设置的谷歌两个

**Comment by joshatt** [comment]
@lsc183754539 
刚刚试了改成wireless network connection, 可以运行了. 不过youtube只能浏览页面, 视频不行,始终在转圈.

**Comment by MarvellousBaby** [comment]
@joshatt q请问你解决了吗这个问题，我也是都出来了但是上不了网

**Comment by huanjue** [comment]
视频问题，建议走SNI：）

**Comment by MarvellousBaby** [comment]
@sandByMe   请问你的可以了吗，我也是都出来了，但是翻不了墙

**Comment by sandByMe** [comment]
@MarvellousBaby  不可以啊。作者也没回复我。我也不清楚为什么

**Comment by downature** [comment]
@MarvellousBaby 
@sandByMe 
@joshatt 

YouTube播放问题，请自行寻找可用的SNI代理服务器IP，代替dowsDNS/data/wrcd.json中的IP
