### ISSUE TITLE
lede上报错

### ISSUE THREAD

**Issue by cjjdaq** [dowsnature/dowsDNS#35]
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ImportError: No module named requests

另外如何关闭缓存

**Comment by cjjdaq** [comment]
已解决，如何关闭缓存。能否添加后台与退出,加config-dir

**Comment by SeaHOH** [comment]
并没有缓存，只有 data，可以自定义，离开 data 这个程序就没有意义了。

**Comment by cjjdaq** [comment]
只想它让他做dnsmasq的上游，用下119.29的edns-client-subnet

**Comment by SeaHOH** [comment]
两个方案
https://www.v2ex.com/t/334691
https://blog.phoenixlzx.com/2016/04/27/better-dns-with-unbound/

**Comment by cjjdaq** [comment]
就用这个了，清空了data，gfw的给pdnsd的tcp vps的dns，剩下的丢给给dowsDNS。
def Get_myip(ifname = 'pppoe-wan'):
	import socket, fcntl, struct 
	s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
	inet = fcntl.ioctl(s.fileno(), 0x8915, struct.pack('256s', ifname[:15])) 
	Myip[0] = socket.inet_ntoa(inet[20:24])  
只是，pppoe重新拨号了，要重启dowsDNS获取wan口ip吗？

**Comment by cjjdaq** [comment]
Public_Server到底是要true还是要false呀，糊涂了

**Comment by downature** [comment]
@cjjdaq  可以不需要，因为ISP给你的公网IP一般都是一个网段的。如果给的是内网IP，建议用自带的函数获取公网IP

**Comment by cjjdaq** [comment]
用作dnsmasq上游，过几个小时就解析不了，囧。

**Comment by downature** [comment]
@cjjdaq 应该是程序挂掉了。路由不建议运行python写的程序
