### ISSUE TITLE
管理员命令都没用

### ISSUE THREAD

**Issue by anlexN** [dowsnature/dowsDNS#37]
![default](https://user-images.githubusercontent.com/8686739/27260902-fcdc5764-5469-11e7-904e-9d5075f2faae.PNG)

**Comment by zyqf** [comment]
尝试修改127.0.0.1为0.0.0.0

**Comment by downature** [comment]
修改config.json中的"Local_dns_server" : "127.0.0.1",值，127.0.0.1改为0.0.0.0

**Comment by anlexN** [comment]
连接成功。但是youtube看不了，请问如何解决youtube问题？个人感觉youtube天生就是host科学上网的硬伤。为什么呢？我不可能天天跟youtube团队反馈视频播放不了
