### ISSUE TITLE
zero length field name in format

### ISSUE THREAD

**Issue by codexss** [dowsnature/dowsDNS#4]
On the client:
C:\Users\Lentin>nslookup google.com 123.206.xx.xx
服务器:  UnKnown
Address:  123.206.27.92

DNS request timed out.
    timeout was 2 seconds.
名称:    google.com
Address:  2404:6800:4008:802::200e

Server(centos 6.7) Errorlogs:
[root@VM_91_149_centos dowsDNS]# python dns.py
zero length field name in format
zero length field name in format
zero length field name in format

**Comment by downature** [comment]
ipv6不支持

**Comment by codexss** [comment]
可是我是ipv4的网络并且请求的也是ipv4的地址啊。。
downature <notifications@github.com>于2017年1月1日 周日11:30写道：

**Comment by bash-horatio** [comment]
@codexss 从这段来看
```
DNS request timed out.
timeout was 2 seconds.
名称: google.com
Address: 2404:6800:4008:802::200e
```
确实是在找google的ipv6地址，本地hosts配的？

**P.S.你的公网ip只给指令打了码，输出没有!**

**Comment by downature** [comment]
@codexss 
你下载最新版本的试试？

腾讯云主机配置应修改为：

"Local_dns_server" : "0.0.0.0",


我屏蔽了IPv6的解析

**Comment by codexss** [comment]
@downature 问题依旧，不过客户端没有解析出ipv6了，但是ipv4的地址还是解析不出来。
![](https://cloud.githubusercontent.com/assets/5959201/21750848/05672e0e-d5f8-11e6-9189-28ab3cab0cfd.png)

**Comment by l5h5t7** [comment]
一些奇葩网络下使用非白名单中的 DNS 递归服务器会丢包，但是 TCP 连接正常。

**Comment by downature** [comment]
@codexss 

最新版本已经修复了这个问题

https://github.com/dowsnature/dowsDNS/pull/17

**Comment by theratlesnake** [comment]
@downature 老大，问下，貌似youtube可以打开，但是播放不了视频啊？可以解决么

**Comment by wpyok500** [comment]
win版的0.23.3什么时候编译，还是可以直接下载源文件覆盖。

**Comment by zyqf** [comment]
@wpyok500 下次功能更新，不可以直接下载源文件，但是可以配置python 来运行

**Comment by downature** [comment]
@wpyok500 不可以下载源文件覆盖，请配置Python环境运行最新的版本
