### ISSUE TITLE
不工作

### ISSUE THREAD

**Issue by YaoQii** [dowsnature/dowsDNS#45]
我在mac windows ubuntu都尝试后，发现大神的这个作品为何现在不能科学上网了？
我的做法：
1、将 conf/config.json 中的 Local_dns_server 的值改为电脑的 127.0.0.1， 同时修改本地ip：etc/resolv.conf为127.0.0.1
2、在 /etc/resolvconf/resolv.conf.d/base（原本为空文件） 里添加 nameserver 127.0.0.1
     sudo resolvconf -u
    sudo systemctl restart network-manager.service 但是提示没有systemctl: command not found
3、运行：python2 run.pu
4、重启chrome，还是不能够Google。
请问一下是封了？

**Comment by Toddgh** [comment]
我猜可能墙又升高了

**Comment by omaidb** [comment]
Gfw出口部署了CA重置，hosts彻底没戏了
