### ISSUE TITLE
提示“No module named ‘requests’”

### ISSUE THREAD

**Issue by CXZS-Git** [dowsnature/dowsDNS#47]
D:\Onedrive\文档\GitHub\dowsDNS>py start.py
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

上述提示在两台电脑上均出现了。
我本机是Python 3环境，办公电脑是Python 2环境。

**Comment by chensongbin** [comment]
就是说你缺少requests模块，需要先安装requests模块

**Comment by CXZS-Git** [comment]
执行了“pip install requests”就能成功运行了。
感谢。
