### ISSUE TITLE
你他娘的就不能在简介里放上下载链接吗

### ISSUE THREAD

**Issue by omaidb** [dowsnature/dowsDNS#5]
你他娘的就不能在简介里放上下载链接吗？每次要找好久才下载到。另外，要不要做个ppa，这样就可以随时更新了。

**Comment by OscarGong** [comment]
![image](https://cloud.githubusercontent.com/assets/7035787/21581963/e6d84a52-d081-11e6-805e-d416b2233155.png)
已经举报了

**Comment by YiuTerran** [comment]
智障楼主啊。。

**Comment by omaidb** [comment]
好吧，太激动了。
在 2017年01月03日 17:42, tryao 写道:

**Comment by l5h5t7** [comment]
点一下 release 不就能看到了？照理说常混 GitHub 的不会不知道吧！
