### ISSUE TITLE
测试了一下……感觉有点多余……

### ISSUE THREAD

**Issue by do21** [dowsnature/dowsDNS#7]
我试用了一下，这个程序是在本地搭了一个小DNS，并根据 rpz.json 里面的记录来提供白名单解析，如果名单里面没有，就返回 remote_dns_server 的查询结果，是这样吗？

如果我没猜错的话，里面有两个问题：
1. 白名单有自动更新机制吗？失效后怎么办？既然是放在安装包里的，我猜没有？
2. 修改 Local_dns_server 的意义是什么呢？很多人都是DHCP获得的Client IP，每次都要改很麻烦吧？还是为了开放给内网其它Client呢？

对于问题1，其实用自动更新hosts的脚本会更方便，做成小程序的目的是？性能更好？
对于问题2，修改IP的必要性我建议可以说明一下，如果本机用是否可以保持 127.0.0.1？我试过是可以工作的，那么修改为当前Client IP是为了开放给内网其它Client吗？

如果能加上自动更新，并可以注册为系统service的话应该会更好，对了，我是Windows。

**Comment by theratlesnake** [comment]
请问一下，【然后执行 python dns.py】 这个怎么弄
