### ISSUE TITLE
请问支持局域网内共享这个本地的DNS吗

### ISSUE THREAD

**Issue by hguandl** [dowsnature/dowsDNS#8]
我尝试将手机和电脑连入同一个Wi-Fi，电脑开启这个应用后，把手机的DNS改为电脑的局域网地址，发现好像不好用，是因为我的设置问题还是说这个功能还未添加？此外说明里的Local_dns_server具体指什么？我填的是127.0.0.1，请问还可能有设置成别的情况吗？

**Comment by downature** [comment]
Local_dns_server具体指电脑的局域网地址
