### ISSUE TITLE
win7下可用，特来感谢一下，另外请教点问题

### ISSUE THREAD

**Issue by theratlesnake** [dowsnature/dowsDNS#9]
1.使用这种翻墙方式安全性怎么样？会不会被人获取到真实地址？
2.本人对网络不太懂，但是这种翻墙方式的生存时间可以持续多久？会不会很快被GFW封？
3.那个DNS文件要更新的吗？
4.我查到好像有网络有经过香港和泰国，请问网速可以提高吗？
谢谢制作者，感谢。 @downature

**Comment by theratlesnake** [comment]
@jzp820927 大神来关注一下这个项目

**Comment by jzp820927** [comment]
看了下，是个小型 DNS 服务端，怎么了？

**Comment by l5h5t7** [comment]
1. 看你说的安全性是哪方面的安全性，由于不使用类似于 XX-Net 的中间人手段而可以使用原生的 HTTPS 机制，所以不会对数据安全性产生负面影响。由于是直连，所以肯定可以看到真实 IP 。
2. 生存时间还要看墙的意思，很大情况下除了漏网之鱼外这些 IP 能生存的原因也是墙睁一只眼闭一只眼。
3. 要。
4. 由于少数不被封的节点负载高，所以性能上一般都不是很好。不过相比一些垃圾的免费代理来说可能会好很多，但是与你的 ISP 的策略也有一定关系。

**Comment by theratlesnake** [comment]
多谢指教，支持一下作者。
